import { useState } from 'react'

export default function DisclaimerModal({ onAccept }) {
  const [checked, setChecked] = useState(false)

  return (
    <div style={{
      position: 'fixed', inset: 0,
      background: 'rgba(0,0,0,0.75)', backdropFilter: 'blur(6px)',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      zIndex: 1000, padding: 16,
    }}>
      <div className="card" style={{ maxWidth: 480, width: '100%' }}>
        <div style={{ fontSize: 36, marginBottom: 16, textAlign: 'center' }}>⚠️</div>
        <h2 style={{ marginBottom: 12, textAlign: 'center' }}>Important Disclaimer</h2>

        <p style={{ fontSize: 14, marginBottom: 16, lineHeight: 1.7 }}>
          <strong style={{ color: 'var(--text)' }}>Lumos is an educational tool only.</strong><br />
          It does <em>not</em> provide investment advice, financial planning, or regulated financial services.
        </p>

        <div className="disclaimer" style={{ marginBottom: 20 }}>
          The portfolio recommendations generated by this application are based on publicly available market data and AI-generated analysis.
          They should <strong>not</strong> be used as the sole basis for any investment decision.
          Always consult a licensed financial advisor before investing.
        </div>

        <label style={{ display: 'flex', gap: 10, alignItems: 'flex-start', cursor: 'pointer', marginBottom: 20, fontSize: 14, color: 'var(--text-muted)' }}>
          <input
            type="checkbox"
            checked={checked}
            onChange={e => setChecked(e.target.checked)}
            style={{ marginTop: 2, accentColor: 'var(--accent)', width: 16, height: 16 }}
          />
          I understand this app is for educational purposes only and does not constitute investment advice.
        </label>

        <button
          className="btn btn-primary"
          style={{ width: '100%', justifyContent: 'center' }}
          disabled={!checked}
          onClick={onAccept}
        >
          Continue to Lumos →
        </button>
      </div>
    </div>
  )
}
