"""add emotion_tag to holdings

Revision ID: 134d78dbff08
Revises: 034e31d0f523
Create Date: 2026-07-04 19:30:19.938896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134d78dbff08'
down_revision: Union[str, None] = '034e31d0f523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('emotion_tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holdings', 'emotion_tag')
    # ### end Alembic commands ###
