"""add plan and market to users

Revision ID: 38f539c3549e
Revises: 734ca3a12aaf
Create Date: 2026-07-08 19:41:30.813745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38f539c3549e'
down_revision: Union[str, None] = '734ca3a12aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan', sa.String(), server_default='free', nullable=False))
    op.add_column('users', sa.Column('market', sa.String(), server_default='TR', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'market')
    op.drop_column('users', 'plan')
    # ### end Alembic commands ###
