"""add high interest debt to users

Revision ID: f27bcff31ba1
Revises: 00fec5558117
Create Date: 2026-07-20 01:39:21.347012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f27bcff31ba1'
down_revision: Union[str, None] = '00fec5558117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('high_interest_debt', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'high_interest_debt')
    # ### end Alembic commands ###
