"""add primary_fear to users

Revision ID: f887a2a74123
Revises: 134d78dbff08
Create Date: 2026-07-04 21:20:40.273442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f887a2a74123'
down_revision: Union[str, None] = '134d78dbff08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('primary_fear', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'primary_fear')
    # ### end Alembic commands ###
